### ISSUE TITLE
Go 1.13 unwrapping behavior

### ISSUE THREAD

**Issue by akshayjshah** [uber-go/multierr#34]
Go 1.13 introduced `errors.Is`, `errors.As`, and `errors.Unwrap`, all of which inspect errors that implement an optional `Unwrap(error) error` method. Currently, `multierr`'s wrapper type doesn't implement `Unwrap`, so using `multierr.Append` or `multierr.Combine` prevents the standard library from walking the error chain. Is there a good way to extend `multierr` to interoperate with the new stdlib functions?

The main problem is that the standard library's `Unwrap` API expects a linked list of errors, and `multierr` builds a tree. Some options:
* Don't bother. `Is` and `As` don't necessarily make sense for collections of errors anyways.
* Treat the first (or last) error as the "main" error and return it from `Unwrap`. Simple, but not fully correct.
* Something else? It's hard to build an iterator over the error tree, since that introduces yet another wrapper.

**Comment by abhinav** [comment]
What version of multierr are you on? We added support for errors.As and errors.Is in 1.2.0 (#28).
https://github.com/uber-go/multierr/blob/master/CHANGELOG.md#v120-2019-09-26

The `Is` and `As` APIs allow errors to implement the following interfaces to override the default Unwrap-based behavior.

```
interface { As(interface{}) bool }
interface { Is(error) bool }
```

**Comment by akshayjshah** [comment]
🤦‍♂ 1.1.0, so there we have it
