### ISSUE TITLE
Depending on this project ends up pulling in lots of dependencies

### ISSUE THREAD

**Issue by kevinburkemeter** [uber-go/multierr#35]
I vendor dependencies in my project. Due to the "tools.go" imports in this file, I'm now vendoring all of the staticcheck project. This seems like overkill for a library that is designed to handle multiple errors.

Perhaps you could move the imports in tools.go to a different place, like the private repositories at Uber?

**Comment by abhinav** [comment]
Hey, thanks for reporting! This is a good point. This is fixable by moving
tools dependencies into a submodule that is never published.

    ROOT
      |- go.mod   // go.uber.org/multierr
      |- tools/
          go.mod  // go.uber.org/multierr/tools
          tools.go

We'll fix this shortly.

**Comment by kevinburkemeter** [comment]
Thanks!

**Comment by abhinav** [comment]
Oh, a simpler solution is to move tools.go to tools_test.go. Go modules will ignore the test files and their dependencies.

**Comment by abhinav** [comment]
@kevinburkemeter v1.5.0 should not have this issue. Thanks again for reporting.

**Comment by kevinburkemeter** [comment]
Thanks for the fast fix!
