### ISSUE TITLE
go get uber-go / multierr error 

### ISSUE THREAD

**Issue by sximenesamedigital** [uber-go/multierr#43]
# go.uber.org/multierr
../go.uber.org/multierr/error.go:197:6: undefined: errors.As
../go.uber.org/multierr/error.go:210:6: undefined: errors.Is

**Comment by prashantv** [comment]
`errors.As` and `errors.Is` were [added in Go 1.13](https://blog.golang.org/go1.13-errors).

Similar to Go, we only [support](https://github.com/uber-go/multierr/blob/master/go.mod#L3) the current (Go 1.15) & previous (1.14) releases.

Please try with a newer Go version.
