### ISSUE TITLE
Support multierr.Every

### ISSUE THREAD

**Issue by kdeberk** [uber-go/multierr#66]
Hello,

There seems to be a correctness issue the implementation of `multiError.Is`. I say "seems" because I cannot find any consensus on what `errors.Is(err, ErrIgnorable)` should actually be doing when `err` is a `multiError` containing both ErrIgnorable and an important error (that you *do* want to handle). 

Perhaps `Is` should only return true if all contained errors match the target, so instead
```
func (merr *multiError) Is(target error) bool {
        if len(merr.Errors()) == 0 {
                return false
        }
	for _, err := range merr.Errors() {
		if !errors.Is(err, target) {
			return false
		}
	}
	return true
}
```
an alternative would be that `Is` is not implemented at all, and then `errors.Is` should return false.

Again, I don't know if the golang developers ever specified some semantics for `errors.Is`, but I think that from both an intuitive and practical sense, `errors.Is(err, ErrIgnorable)` should return false. Intuitive, because a multiError is not equal to a single error, and practical because if the important error is not represented by a value, e.g. `val ErrImportant = errors.New(...)`, then there is no way to easily ignore only ignorable error without calling `Errors()` and iterating over the individual errors..

**Comment by tchung1118** [comment]
We agree that this would be a good convenience feature to add to multierr, but we're still considering if this should work with `errors.Is` or should be provided as a separate function from this package.

**Comment by abhinav** [comment]
FWIW, the standard library's `errors.Join` matches multierr's behavior.
`errors.Is` will return true if any of the errors in a `errors.Join`-ed error matches.
Despite the name, `errors.Is` is not an equality check but an approximate match.

Perhaps we need an "all" variant of Is (`multierr.AllAre` or `multierr.Every`?), where every error in the multierr list gets an `errors.Is` call individually, but not at the top-level of the multierr.

**Comment by r-hang** [comment]
Internal ref: GO-1932
