### ISSUE TITLE
Set minimum permissions to workflows

### ISSUE THREAD

**Issue by gabibguti** [uber-go/multierr#76]
Setting minimum permissions to workflows is important to keep your repository safe against supply-chain attacks. GitHub grants a GITHUB_TOKEN with higher permissions than necessary by default for workflows. With higher permissions, if your workflow suffers an attack, the attacker would be able to push malicious code to your repository for example. To avoid that, we set minimum permissions.

I see both workflows, `fossa.yaml` and `go.yml`, don't need much permissions, so setting `contents: read` should be enough. If you agree with the changes, I can open a PR!

This is considered good-practice and recommended by [GitHub](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

##### Additional context

I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by abhinav** [comment]
Thanks, @gabibguti!
We'll make the change.
